#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
debug: true
#名称
server_name: "dev"
#server 地址
server_url: "0.0.0.0:8000"
#缓存介质类型,单选("mem","redis")
cache_type: "mem"
#redis地址(cache_type为“redis”时有效)
redis_url: "redis://139.159.254.27:31478"
#数据库地址
database_url: "mysql://tdnis:Tdcarefor123@122.9.125.181:13306/rust_test"
#逻辑删除字段
logic_column: "del"
logic_un_deleted: 0
logic_deleted: 1
#日志文件存放目录
log_dir: "target/log/"
#日志通道最大缓存日志条数
log_cup: 10
#日志分割尺寸-单位KB,MB,GB
log_temp_size: "100MB"
#日志打包格式可选“”（空-不压缩）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
log_pack_compress: "zip"
#日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
log_rolling_type: "All"
#日志等级-info,error,warn,debug,trace
log_level: "debug"
#JwtToken秘钥
jwt_secret: "abs_admin"
#短信通道缓存（系统先把数据放入队列sms:send:，第三方短信sdk或程序需要从队列获取并发送，获得回执存入sms:resp:*）,格式为sms:send:手机号和sms:resp:手机号
sms_cache_send_key_prefix: "sms:send:"
#登陆失败拒绝策略，重试次数限制(0次无限制)
login_fail_retry: 3
#登陆失败重试次数限制超过后提示的等待时间（秒）
login_fail_retry_wait_sec: 30

keycloak_auth_server_certs: "http://122.9.125.181/auth/realms/tdcare/protocol/openid-connect/certs"



#接口白名单（免登陆直接访问）
white_list_api:
 - "/"
 - "/test"
 - "/test/keycloak"
 - "/admin/sys_login"
 - "/admin/captcha"


