[package]
name = "abs_admin"
version = "0.1.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rbatis orm dep
rbatis = { version = "2.1", default-features = false, features = ["mysql","tokio1"] }
#serde and json
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
#static
lazy_static = "1.4.0"
#log
log = "0.4"
fast_log = { version="1.3", features = ["lz4","zip", "gzip"]}
#futures
futures = "0.3"
#web server
actix-web = "3.3"
actix-http = "2.2"

#redis
redis = {version = "0.20", features = ["async-std-comp"] }
#jwt
jsonwebtoken = "7"
#snowflake
rustflake = "0.1.0"
md5 = "0.7.0"
yaml-rust = "0.4"
#captcha
captcha = "0.0.8"
#http client,use rust-tls replace to native tls
reqwest = { version = "0.10",default-features = false, features = ["json","rustls-tls","blocking"] }
#tokio = { version = "1.11.0", features = ["full"] }
#image code
image = "0.23"
#async trait
async-trait = "0.1"

async-std = "1.10.0"

hyper = { version = "0.14", features = ["full"] }